djangoSuperUserEmail: ENC[AES256_GCM,data:hi+ZWcENFGKlU84LR/yli0A=,iv:Zgfz+8x1PLhDL0rHd4idH21hPmAslw8mWXzknC5i9MM=,tag:533v4b/1y1mDD7C2nBqGsw==,type:str]
djangoSuperUserPass: ENC[AES256_GCM,data:AAsV3FuAZJ5QzIlyOw==,iv:YfeWOEqgZHQxmI6IfPOWHPRoMyaej6SJH7OUgj8yDWQ=,tag:VXJ/VhzcqE/WarwjPxzIvg==,type:str]
djangoSecretKey: ENC[AES256_GCM,data:/JVAyc96seMRTiyGEw/0hSSacKfFC4eQXJGo+Nu5ngAicrnHJqPa0fq9pJq63kLfLgU=,iv:gdMfxI8HrzmdcdV4C+VfgxikT/O6SptQFmkRhikS52U=,tag:O7xSA14bQtcxNb8sZwZh9g==,type:str]
oidc:
    clientId: ENC[AES256_GCM,data:qFMt3wOxi2N/SLbHsw3nlqYjXCkcW8Dk1tJ1GexM9nlnhuLO,iv:bQpKzMNZv2Kcm6blDWJwbKiSjUAFjVwEUalLqgylaTY=,tag:Wm4NioIktA+p9XWldEWDbw==,type:str]
    clientSecret: ENC[AES256_GCM,data:MiYBGSyuJDcf1f8//7p6L1SIY/4f0f7lKA7OLcbojaZ28q8hh8cr0fPU9s+ftfQe4Ztxg/0wSX/QSUEP4DtiXg==,iv:HrbljXaj2Ki6ElINPoVvaZqn4gyThBLT4SKQDJ0oJrA=,tag:N5i1vqqxlMX7nOb2ymGFHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15fyxdwmg5mvldtqqus87xspuws2u0cpvwheehrtvkexj4tnsqqysw6re2x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreXo5bDRITnYyVE8wODBC
            RkVsRlc1V1dZZHltYWg1UTRBcjAwK3pJSkFvCmlmczNPMVVsU1lSRHhTWStiZEN6
            ZXFhcFcvaXVEMHJtWXdWV3lDUlhaR3MKLS0tIFZ1R0hHVEttUWY3T1pHTUwrU2Zn
            TFJzd2ZHZFFmSFdwY0YyYmd6dnFRQkUKJH+7TZtZvl/L6vRq9gwhDhWj7gmcq8Zn
            WlYcRcrqNDBweDwSlER80DhF0xuS0Ero0bh9cr/HiFPwZZ6RxUJoHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16hnlml8yv4ynwy0seer57g8qww075crd0g7nsundz3pj4wk7m3vqftszg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UU9nenMwZDlrTkJOZzZu
            dmVvVWlBKy9wTVVlRFlybzJldDJoZ0xjOTBvClIyL3M0TTFtL1UxaitnZUNGZXlO
            ZVRYVDBsYXphaTZ4TmdGbXJFOHpMMzQKLS0tIFdJSkk4NnZMYTJtSE5sMVoyYU9Z
            bjlkVG1QQnVXUXhuK2JXN2ZnWmtQeE0KGbOeGa2hIPrrDcfQ64GEjTR0ZeCyIIZK
            2bxSivdOw+1I96+OOIqjvGaa12FfPI58uizldaI0+hSY77vT4sr/7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1plkp8td6zzfcavjusmsfrlk54t9vn8jjxm8zaz7cmnr7kzl2nfnsd54hwg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVnhHdmpjK2hsd2d4Mk1Y
            UlE4NHdjNHAwbGM4K0ZOVFkzd0JiOTNzYW00Ck9sVnoyRXJFa2F1SnVxemV3b016
            MzJzZUNrVVNPYlhkM2hDK0ZiMEpCNmcKLS0tIEdseGhqZ1dLeGh0TE1tSDRldWVk
            M0hDVGJaN2Jmc004TFYzSGJOTEVDNVUKB3TenK4RxkoGRAzX2AlcbyCddGfHte3N
            mSEUuy0ig2tlF0eL0yA5GR8BIfGEEMQS6tJCliUsKwC6M233mkD0tQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12g6f5fse25tgrwweleh4jls3qs52hey2edh759smulwmk5lnzadslu2cp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdHFEeVUyL3d4WVdNaTJ1
            SU9PaG1vSG5YUXpobFhCbnhhNlpwWGZaaldvCkFrWTBSNWdWOVlBeU1sQWUyTlFy
            QVk5QjJ2UmNhRmVVMFgxZ1lpdzNKVmMKLS0tIHF5VjVJcVV3Zk5uUFhIZEljMzAx
            SUNyejQ4alppMC9tanRFeCtBcndHaTAKfBO4hj5T/bdwbvK8hbEvcAcjuLA7oxg9
            eSWcPZp27LhXMaEwnDlFnLDFEMic/WU6HQBYcSCpt+n98Y4z9T1q2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qy04neuzwpasmvljqrcvhwnf0kz5cpyteze38c8avp0czewskasszv9pyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UGxFUlhiVDNIRTVhdjNO
            ZEZLcDhrUjNNOGZ6a0lvcFRQa0pwMjYyL0hnCmIyQ2tTVXRocFRvNmVkVENXVUEx
            YnpySzF5RXA1djlMSlhhcjRVdlliTmsKLS0tIGtwb2x1cmlKMTkzTUxENi9NK2ZI
            b2dKNENuQmorTXZtdVhLNGo5UVBPZzgK1gaZkRtxV+BVO1lX25XXAonvyrK7V48d
            oAHG/v2OyD7dJJKYmHyIcrWLCRplgQb2r7t6gLSr0llf9rbWQhmkiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-24T10:35:08Z"
    mac: ENC[AES256_GCM,data:A6YUQM3N2DwqjPILfPT4Nc6vlpu52c8qa2+5OJABL2cz6jzvhO2e/0CzJl7P/bOYhlYMpHHeCTX3jk2DMyppuDJsqBN5ouw2oDe/S8WOC9xaKWRxqlgkD93K8ZCYGad9sS58BJN3upBEjln+yu/2trihOsEi6pCQkB/Jrmbe+Qo=,iv:SRgaH9W6FApY8qf8HGfdMpiErx+FOnJJBAd/op93Bxg=,tag:IlDeS9weVroGKhOvU3xwAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
