# Generated by Django 5.1 on 2024-09-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_document_is_public_alter_document_link_reach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_e2ee',
            field=models.BooleanField(default=False),
        ),
    ]
