# Generated by Django 5.1.2 on 2024-10-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fix_users_duplicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='link_reach',
            field=models.CharField(choices=[('restricted', 'Restricted'), ('authenticated', 'Authenticated'), ('public', 'Public')], default='restricted', max_length=20),
        ),
    ]
